# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebcaf8217cc0588a4042e7611631573a9856e212f89b1aa9d64803860b0d16454692ccfa7dc8c3f164a9f0a13b48f62297e72dc8cc75c579da153cc5c93e7713

test:
  secret_key_base: 9fadfe558653688d3335365926b031d7af42594ceda263cb40641adbfe22931adb0793f8653a881ce689de25b0ab5f5250d832f83536cffa61ee6e6b75c449e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
